---
- name: Request a restart of all stale components
  delegate_to: localhost
  run_once: true
  uri:
    url: '{{ ambari_url }}/api/v1/clusters/{{ ambari_cluster_name }}/requests'
    body: "{{ lookup('template', 'restart.json.j2') }}"
    timeout: '{{ ambari_http_timeout }}'
    method: POST
    force_basic_auth: yes
    user: '{{ ambari_user }}'
    password: '{{ ambari_password }}'
    return_content: yes
    headers:
       X-Requested-By: ambari
       Content-Type: text/plain
    status_code: 201,202
    validate_certs: no
    body_format: json
  register: ambari_restart_request
  changed_when: ambari_restart_request.content
  listen: restart stale components

- name: wait stale component restart
  delegate_to: localhost
  run_once: true
  uri:
    url: "{{ ambari_restart_request.json['href'] }}"
    timeout: '{{ ambari_http_timeout }}'
    method: GET
    force_basic_auth: yes
    user: '{{ ambari_user }}'
    password: '{{ ambari_password }}'
    return_content: yes
    headers:
      X-Requested-By: ambari
      Content-Type: text/plain
    validate_certs: no
    status_code: 200
  register: ambari_restart_response
  delay: '{{ ambari_http_delay }}'
  retries: '{{ ambari_http_retries }}'
  until: ambari_restart_response.json['Requests']['request_status'] == 'COMPLETED'
  when: ambari_restart_request.content
  listen: restart stale components
